# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'task2_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for task2_app
  pod 'TinyConstraints', '~> 4.0'

end
